### ISSUE TITLE
Machine crash caused VM to create new default machine

### ISSUE THREAD

**Issue by jp-gorman** [docker/toolbox#351]
I had a docker default machine with many images as a host that was running. My MacBook Pro crashed and upon restart the default machine (an it's disk) had been replaced by a new default machine with a blank disk (effectively loosing entire host disk content).

This has now happened 3 times to me, so it's not a one off. Even when I placed the disk outside the machine folders, I noted that removal, removes any attached disk also (might not be the best idea, or at least give an option not to)

So with this happening I backed up the disk, but now cannot create a new default machine and reuse the saved disk. Once I restart I get some network errors.

Last login: Wed Dec 16 15:35:24 on ttys000
bash --login '/Applications/Docker/Docker Quickstart Terminal.app/Contents/Resources/Scripts/start.sh'
Error checking TLS connection: Error trying to get host state: machine does not exist
Error getting IP address: machine does not exist
MacBookPro:~ user$ bash --login '/Applications/Docker/Docker Quickstart Terminal.app/Contents/Resources/Scripts/start.sh'
Error checking TLS connection: Error trying to get host state: machine does not exist
Error getting IP address: machine does not exist

Thanks

John.

**Comment by jeffdm** [comment]
Thanks for the issue. If the machine is detected as _not_ existing, then the Quickstart Terminal will clear anything that exists. Looking into this further.

**Comment by jp-gorman** [comment]
Just FYI - Another crash (I really gotta sort whatever that is also) but another docker machine reset to default!! Hope my TimeMachine can save me this time, but it's really bad from docker perspective.

**Comment by jeffdm** [comment]
Thanks for the update

**Comment by jp-gorman** [comment]
OK, now I'm getting mad. I had a huge host of images on the host and the toolBox has again just wiped the entire machine. I see on virtualbox the old default did exist, and is now showing the following error:

Machine UUID {85718972-6338-427e-abf7-122bf245f63a} in '/Users/xxxxxxxx/.docker/machine/machines/default/default/default.vbox' doesn't match its UUID {98016809-5277-4fe8-9503-bb51a9de381d} in the registry file '/Users/xxxxxxxxx/Library/VirtualBox/VirtualBox.xml'.
Result Code: 
NS_ERROR_FAILURE (0x80004005)
Component: 
MachineWrap
Interface: 
IMachine {f30138d4-e5ea-4b3a-8858-a059de4c93fd}

This clearly shows that the machine did exist in the Virtual Machine, then Docker Toolbox cleared out the "default" machine with a new disk and so the old "default" cannot find it's disk.

This is pretty shocking stuff, you just wiped the machine even though it already existed and replaced with a new one.

I need someone to review this or I have to look for a new container technology - This is simply not good enough (frankly it's shocking). Your turn around on data loss is pretty slack.

I was a real big docker fan, but this toolset has cost me weeks of effort every time it blows my work away. I also spent days trying to fix that stupid "error 255" issue the tool has also that blows away the network connections.....productivity on docker now approaching 0!

**Comment by jeffdm** [comment]
@jp-gorman I'm very sorry to hear this wiped your VM again. This is a rare bug where VirtualBox reports the VM as not existing (returning error code `-1`). This error will cause the QuickStart Terminal or Kitematic to erase the VM in case there are leftover files that would cause re-creating it to fail.

I'm working on a fix immediately to not trust this assumption. Sorry again for having your container and image data gone due to this.

**Comment by jeffdm** [comment]
See #375 - fix on the way!

**Comment by jp-gorman** [comment]
Great - Thanks Jeff - Any ideas when this will go live ? 

Be really nice to test that pulling the plug on OSX (say with 0 battery to force complete death) upon recovery (when you want apps opened) to recover correctly and when restart of kitematic (test 1 crash case) or restart of toolbox terminal (test 2 crash case) and note the "default" machine is present. I could not tell what your VM Error case referred to...

**Comment by jeffdm** [comment]
@jp-gorman just built: https://github.com/docker/toolbox/releases/tag/v1.9.1j

**Comment by jeffdm** [comment]
Should be fixed in `1.9.1j` or above.

Thanks again @jp-gorman !

**Comment by ctliv** [comment]
Issue still occurs on 1.10.x. 

Here is the output of "docker version":

Client:
 Version:      1.10.1
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   9e83765
 Built:        Thu Feb 11 19:14:21 2016
 OS/Arch:      windows/amd64

Server:
 Version:      1.10.3
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   20f81dd
 Built:        Thu Mar 10 21:49:11 2016
 OS/Arch:      linux/amd64

Here the issue in VirtualBox:

Machine UUID {30a8766a-3497-41dc-9fc0-7dff5ac90405} in 'C:\Users\[...]\.docker\machine\machines\default\default\default.vbox' doesn't match its UUID {8f81131a-3dc3-48e1-95b9-e3103a083b63} in the registry file 'C:\Users\[...].VirtualBox\VirtualBox.xml'.
Exit code: 
E_FAIL (0x80004005)
Component: 
MachineWrap
Interface: 
IMachine {f30138d4-e5ea-4b3a-8858-a059de4c93fd}

Issue should be reopened.

**Comment by talktejas** [comment]
Issue is also occuring on docker 1.13.1 on Windows.

For some reason docker wipes out old machine and replaces it with a new default machine.

Virtual box still shows the old default image that is inaccesible as UUID doesn't match.

This makes docker totally unreliable.
