### ISSUE TITLE
VBoxManage.exe: error: Context: "LockMachine(a->session, LockType_Write)" at line 493 of file VBoxManageModifyVM.cpp

### ISSUE THREAD

**Issue by yugou** [docker/toolbox#360]
Donwloaded DockerToolbox-1.9.1f.exe and kicked off Docker Quickstart Terminal on Windows 10.
Did not go well.

So switched to CLI as following and always ends up with the error.
> VBoxManage.exe: error: Context: "LockMachine(a->session, LockType_Write)" at line 493 of file VBoxManageModifyVM.cpp

PS C:\Program Files\git\bin> docker-machine rm -f default
Successfully removed default

PS C:\Program Files\git\bin> docker-machine --debug create -d virtualbox default
Launching plugin server for driver virtualbox
Plugin server listening at address 127.0.0.1:52239
() Calling .GetVersion
Using API Version  1
() Calling .SetConfigRaw
() Calling .GetMachineName
(flag-lookup) Calling .GetCreateFlags
Making call to close connection to plugin binary
Making call to close driver server
(flag-lookup) Calling .Close
Successfully made call to close driver server
Found binary path at C:\Program Files\Docker Toolbox\docker-machine.exe
Launching plugin server for driver virtualbox
Plugin server listening at address 127.0.0.1:52243
() Calling .GetVersion
Using API Version  1
() Calling .SetConfigRaw
() Calling .GetMachineName
(default) Calling .GetMachineName
(default) Calling .DriverName
(default) Calling .GetCreateFlags
(default) Calling .SetConfigFromFlags
Running pre-create checks...
(default) Calling .PreCreateCheck
(default) DBG | COMMAND: C:\Program Files\Oracle\VirtualBox\VBoxManage.exe --version
(default) DBG | STDOUT:
(default) DBG | {
(default) DBG | 5.0.12r104815
(default) DBG | }
(default) DBG | STDERR:
(default) DBG | {
(default) DBG | }
(default) DBG | COMMAND: wmic cpu get VirtualizationFirmwareEnabled
(default) DBG | STDOUT:
(default) DBG | {
(default) Calling .GetConfigRaw
(default) DBG | VirtualizationFirmwareEnabled
(default) DBG | TRUE
(default) DBG |
Creating machine...
(default) DBG | }
(default) Calling .Create
(default) Creating VirtualBox VM...
(default) Creating SSH key...
(default) DBG | Creating disk image...
(default) DBG | Creating 20000 MB hard disk image...
(default) DBG | COMMAND: C:\Program Files\Oracle\VirtualBox\VBoxManage.exe createvm --basefolder C:\Users\norio\.docker\
machine\machines\default --name default --register
(default) DBG | STDOUT:
(default) DBG | {
(default) DBG | Virtual machine 'default' is created and registered.
(default) DBG | UUID: 5bddafef-3398-42c2-a13e-da517f3c7699
(default) DBG | Settings file: 'C:\Users\norio\.docker\machine\machines\default\default\default.vbox'
(default) DBG | }
(default) DBG | STDERR:
(default) DBG | {
(default) DBG | }
(default) DBG | VM CPUS: 1
(default) DBG | VM Memory: 1024
(default) DBG | COMMAND: C:\Program Files\Oracle\VirtualBox\VBoxManage.exe modifyvm default --firmware bios --bioslogofa
dein off --bioslogofadeout off --bioslogodisplaytime 0 --biosbootmenu disabled --ostype Linux26_64 --cpus 1 --memory 102
4 --acpi on --ioapic on --rtcuseutc on --natdnshostresolver1 off --natdnsproxy1 off --cpuhotplug off --pae on --hpet on
--hwvirtex on --nestedpaging on --largepages on --vtxvpid on --accelerate3d off --boot1 dvd
(default) DBG | STDOUT:
(default) DBG | {
(default) DBG | }
(default) DBG | STDERR:
(default) DBG | {
(default) DBG | VBoxManage.exe: error: Code E_FAIL (0x80004005) - Unspecified error (extended info not available)
(default) DBG | VBoxManage.exe: error: Context: "LockMachine(a->session, LockType_Write)" at line 493 of file VBoxManage
ModifyVM.cpp
(default) DBG | }
notifying bugsnag: [Error in driver during machine creation: C:\Program Files\Oracle\VirtualBox\VBoxManage.exe modifyvm
default --firmware bios --bioslogofadein off --bioslogofadeout off --bioslogodisplaytime 0 --biosbootmenu disabled --ost
ype Linux26_64 --cpus 1 --memory 1024 --acpi on --ioapic on --rtcuseutc on --natdnshostresolver1 off --natdnsproxy1 off
--cpuhotplug off --pae on --hpet on --hwvirtex on --nestedpaging on --largepages on --vtxvpid on --accelerate3d off --bo
ot1 dvd failed:
VBoxManage.exe: error: Code E_FAIL (0x80004005) - Unspecified error (extended info not available)
VBoxManage.exe: error: Context: "LockMachine(a->session, LockType_Write)" at line 493 of file VBoxManageModifyVM.cpp
]
Error creating machine: Error in driver during machine creation: C:\Program Files\Oracle\VirtualBox\VBoxManage.exe modif
yvm default --firmware bios --bioslogofadein off --bioslogofadeout off --bioslogodisplaytime 0 --biosbootmenu disabled -
-ostype Linux26_64 --cpus 1 --memory 1024 --acpi on --ioapic on --rtcuseutc on --natdnshostresolver1 off --natdnsproxy1
off --cpuhotplug off --pae on --hpet on --hwvirtex on --nestedpaging on --largepages on --vtxvpid on --accelerate3d off
--boot1 dvd failed:
VBoxManage.exe: error: Code E_FAIL (0x80004005) - Unspecified error (extended info not available)
VBoxManage.exe: error: Context: "LockMachine(a->session, LockType_Write)" at line 493 of file VBoxManageModifyVM.cpp

**Comment by FrenchBen** [comment]
Sounds like you're having some path issues.

1. Right click on "This PC" / "My Computer" on windows desktop
2. Select "Properties"
3. Go to "Advanced" tab
4. Click "Environment Variables..." at the bottom
5. Under System Variables click "New..."
6. Set "Variable name" to "VBOX_INSTALL_PATH"
7. Set "Variable value" to "C:\Program Files\Oracle\VirtualBox\" (or where your vbox is installed)
8. Select "OK" and close all the other settings windows

**Comment by yugou** [comment]
Arigatou, FrenchBen

It has been set and conducted my operations under the env var set.

C:\Windows\System32>env | grep VBOX
VBOX_INSTALL_PATH=C:\Program Files\Oracle\VirtualBox\
VBOX_USER_HOME=C:\Users\norio\.VirtualBox

C:\Windows\System32>cd %VBOX_INSTALL_PATH%
C:\Program Files\Oracle\VirtualBox>ls
DbgPlugInDiggers.dll    VBoxEFI32.fd              VBoxSVC.exe
...

**Comment by FrenchBen** [comment]
Doitamashite @yugou  - Is it working now? or still having the same issue?

**Comment by yugou** [comment]
The reported glitch was under VBOX_INSTALL_PATH var set.

**Comment by FrenchBen** [comment]
Good to hear it's working

**Comment by yugou** [comment]
No, it's NOT working.

**Comment by FrenchBen** [comment]
I thought from above, you said the glitch was in the VBOX_INSTALL_PATH ?
Can you try to uninstall Virtualbox and re-install it?

**Comment by yugou** [comment]
Sorry for the confusion.
Irrespective of VBOX_INSTALL_PATH is set or not, I face the 
VBoxManage.exe: error: Context: "LockMachine(a->session, LockType_Write)" at line 493 of file VBoxManageModifyVM.cpp

I tried re-installation a couple of times, but no luck.

**Comment by FrenchBen** [comment]
Can you open Virtualbox and confirm that the 'default' machine has been created and that you can manually start/stop it?

**Comment by yugou** [comment]
Although the error, yes, a half cooked default is created and able to start/stop.
Why I say "a half cooked" because
1. Starting it on VirtulBox Manager, but I do not get the console so cannot operate in the default OS.
2. My Windows is x64, but the default OS was created as 32bit Linux.

> What anti-virus are you running?
No anti-virus running on my Windows, but only Defender.
In case, I turned off the Defender and tried the same, but resulted in the same error.

![vmdefaulterror](https://cloud.githubusercontent.com/assets/8205302/12103248/0b3b0ea0-b384-11e5-9c1f-97cfcac45c6f.jpg)

**Comment by FrenchBen** [comment]
It's very difficult for me to help when this isn't something happening on my OS and also very specific to VirtualBox - Can you provide a screenshot of the interface that exist for this VM?
Adapters + Host-Only Adapters

**Comment by yugou** [comment]
Is this enough, FrenchBen?

![ipconfig](https://cloud.githubusercontent.com/assets/8205302/12104965/b0934728-b393-11e5-891f-d8ce7b620479.jpg)

**Comment by FrenchBen** [comment]
Could you give me the screenshots from the Virtualbox App? I'm more familiar with those. 

Thanks!

**Comment by yugou** [comment]
Ok, sure.

![host-only networks](https://cloud.githubusercontent.com/assets/8205302/12129673/719ab9ba-b448-11e5-9516-5b84d07ed5c9.jpg)

Arigatou

**Comment by FrenchBen** [comment]
I think that's your issue - You should have 1 Host-Only network interface setup to use 192.168.99.100. Yours isn't setup like that. 
You can delete it, delete the VM and then re-open kitematic to get a fresh VM created. 

There's some info in the wiki:
https://github.com/docker/kitematic/wiki/Common-Issues-and-Fixes#kitematic-vm-stuck-at-99-or-cannot-pull-images

**Comment by yugou** [comment]
> You can delete it, delete the VM and then re-open kitematic to get a fresh VM created.

The same error occurred.

Then referenced to https://github.com/docker/kitematic/wiki/Common-Issues-and-Fixes#kitematic-vm-stuck-at-99-or-cannot-pull-images.
Added 2 adapters: one of which with 192.168.99.100.

![host-only networks_2](https://cloud.githubusercontent.com/assets/8205302/12157463/3c7b6dce-b515-11e5-89fd-6687700d6d98.jpg)

[defaultCreateError.txt](https://github.com/docker/toolbox/files/80482/defaultCreateError.txt)

The same error. No luck.

**Comment by FrenchBen** [comment]
don't add the adapters manually - remove them all and let Kitematic add them. 
You should see a pop-up asking for permission to add them, click on 'allow' when that happens

**Comment by yugou** [comment]
FrenchBen san

> don't add the adapters manually - remove them all and let Kitematic add them. 

I did what you indicated many times before posting to this #360 issue.

Under fresh env.(No VM, No Host-only Networks), kicked off Kitematic.
I get the same error once again.

![errro kitematic](https://cloud.githubusercontent.com/assets/8205302/12184671/083e5128-b5da-11e5-8e90-40c571be977a.jpg)

[kitematicError.txt](https://github.com/docker/toolbox/files/81848/kitematicError.txt)

**Comment by FrenchBen** [comment]
Gomennasai @yugou (￣(エ)￣)

I am not sure why the virtualbox cannot be created. I'll see if I can re-create in one of my Windows VM

**Comment by rmobis** [comment]
I have the exact same issue.

__Error log from Kitematic:__
```
Encountered an error: Error: Command failed: D:\Program Files\Docker Toolbox\docker-machine.exe -D create -d virtualbox --virtualbox-memory 2048 default
Docker Machine Version: 0.5.6
 build 61388e9
 Found binary path at D:\Program Files\Docker Toolbox\docker-machine.exe
Launching plugin server for driver virtualbox
Plugin server listening at address 127.0.0.1:51756
() Calling .GetVersion
Using API Version 1
() Calling .SetConfigRaw
() Calling .GetMachineName
(flag-lookup) Calling .GetMachineName
(flag-lookup) Calling .DriverName
(flag-lookup) Calling .GetCreateFlags
Found binary path at D:\Program Files\Docker Toolbox\docker-machine.exe
Launching plugin server for driver virtualbox
Plugin server listening at address 127.0.0.1:51760
() Calling .GetVersion
Using API Version 1
() Calling .SetConfigRaw
() Calling .GetMachineName
(default) Calling .GetMachineName
(default) Calling .DriverName
(default) Calling .GetCreateFlags
(default) Calling .SetConfigFromFlags
(default) Calling .PreCreateCheck
(default) DBG | COMMAND: D:\Program Files\Oracle\VirtualBox\VBoxManage.exe --version
(default) DBG | STDOUT:
(default) DBG | {
(default) DBG | 5.0.14r105127
(default) DBG | }
(default) DBG | STDERR:
(default) DBG | {
(default) DBG | }
(default) DBG | COMMAND: wmic cpu get VirtualizationFirmwareEnabled
(default) DBG | STDOUT:
(default) DBG | {
(default) DBG | VirtualizationFirmwareEnabled 
(default) DBG | TRUE 
(default) DBG | 
(default) DBG | }
(default) DBG | local Boot2Docker ISO version: v1.9.1
(default) DBG | COMMAND: D:\Program Files\Oracle\VirtualBox\VBoxManage.exe list hostonlyifs
(default) DBG | STDOUT:
(default) DBG | {
(default) DBG | Name: VirtualBox Host-Only Ethernet Adapter #2
(default) DBG | GUID: babb3887-6511-424f-b293-e4d697b81f6f
(default) DBG | DHCP: Enabled
(default) DBG | IPAddress: 169.254.253.231
(default) DBG | NetworkMask: 255.255.0.0
(default) DBG | IPV6Address: fe80:0000:0000:0000:e444:5aef:ded5:fde7
(default) DBG | IPV6NetworkMaskPrefixLength: 64
(default) DBG | HardwareAddress: 0a:00:27:00:00:00
(default) DBG | MediumType: Ethernet
(default) DBG | Status: Up
(default) DBG | VBoxNetworkName: HostInterfaceNetworking-VirtualBox Host-Only Ethernet Adapter #2
(default) DBG | 
(default) DBG | Name: VirtualBox Host-Only Ethernet Adapter #4
(default) DBG | GUID: 06b589dc-b141-447a-8f63-22d83c5b6049
(default) DBG | DHCP: Disabled
(default) DBG | IPAddress: 192.168.10.1
(default) DBG | NetworkMask: 255.255.255.0
(default) DBG | IPV6Address: fe80:0000:0000:0000:c82b:d8a8:eb0e:ef6a
(default) DBG | IPV6NetworkMaskPrefixLength: 64
(default) DBG | HardwareAddress: 0a:00:27:00:00:00
(default) DBG | MediumType: Ethernet
(default) DBG | Status: Up
(default) DBG | VBoxNetworkName: HostInterfaceNetworking-VirtualBox Host-Only Ethernet Adapter #4
(default) DBG | 
(default) DBG | Name: VirtualBox Host-Only Ethernet Adapter #5
(default) DBG | GUID: 5ff690a3-9832-41fe-a66c-5134e1d2b3ea
(default) DBG | DHCP: Disabled
(default) DBG | IPAddress: 192.168.99.1
(default) DBG | NetworkMask: 255.255.255.0
(default) DBG | IPV6Address: fe80:0000:0000:0000:7120:0a12:a4c2:4b0d
(default) DBG | IPV6NetworkMaskPrefixLength: 64
(default) DBG | HardwareAddress: 0a:00:27:00:00:00
(default) DBG | MediumType: Ethernet
(default) DBG | Status: Up
(default) DBG | VBoxNetworkName: HostInterfaceNetworking-VirtualBox Host-Only Ethernet Adapter #5
(default) DBG | 
(default) DBG | Name: VirtualBox Host-Only Ethernet Adapter #3
(default) DBG | GUID: 84dfb189-bc20-43ae-b752-60ca4f0b24f5
(default) DBG | DHCP: Enabled
(default) DBG | IPAddress: 169.254.144.213
(default) DBG | NetworkMask: 255.255.0.0
(default) DBG | IPV6Address: fe80:0000:0000:0000:ad02:4937:ed59:90d5
(default) DBG | IPV6NetworkMaskPrefixLength: 64
(default) DBG | HardwareAddress: 0a:00:27:00:00:00
(default) DBG | MediumType: Ethernet
(default) DBG | Status: Up
(default) DBG | VBoxNetworkName: HostInterfaceNetworking-VirtualBox Host-Only Ethernet Adapter #3
(default) DBG | 
(default) DBG | Name: VirtualBox Host-Only Ethernet Adapter
(default) DBG | GUID: f8abc7ad-d041-4ef4-aff9-0df3bb151599
(default) DBG | DHCP: Enabled
(default) DBG | IPAddress: 169.254.248.236
(default) DBG | NetworkMask: 255.255.0.0
(default) DBG | IPV6Address: fe80:0000:0000:0000:c8b0:46dc:2e7f:f8ec
(default) DBG | IPV6NetworkMaskPrefixLength: 64
(default) DBG | HardwareAddress: 0a:00:27:00:00:00
(default) DBG | MediumType: Ethernet
(default) DBG | Status: Up
(default) DBG | VBoxNetworkName: HostInterfaceNetworking-VirtualBox Host-Only Ethernet Adapter
(default) DBG | 
(default) DBG | }
(default) DBG | STDERR:
(default) DBG | {
(default) DBG | }
(default) Calling .GetConfigRaw
(default) Calling .Create
(default) DBG | local Boot2Docker ISO version: v1.9.1
(default) DBG | Creating disk image...
(default) DBG | Creating 20000 MB hard disk image...
(default) DBG | Writing magic tar header
(default) DBG | Writing SSH key tar header
(default) DBG | Calling inner createDiskImage
(default) DBG | &{D:\Program Files\Oracle\VirtualBox\VBoxManage.exe [D:\Program Files\Oracle\VirtualBox\VBoxManage.exe convertfromraw stdin C:\Users\Raphael\.docker\machine\machines\default\disk.vmdk 20971520000 --format VMDK] [] <nil> <nil> <nil> [] <nil> <nil> <nil> <nil> false [] [] [] [] <nil>}
(default) DBG | Starting command
(default) DBG | Copying to stdin
(default) DBG | Filling zeroes
(default) DBG | Closing STDIN
(default) DBG | Waiting on cmd
(default) DBG | Converting from raw image file="stdin" to file="C:\Users\Raphael\.docker\machine\machines\default\disk.vmdk"...
(default) DBG | Creating dynamic image with size 20971520000 bytes (20000MB)...
(default) DBG | COMMAND: D:\Program Files\Oracle\VirtualBox\VBoxManage.exe createvm --basefolder C:\Users\Raphael\.docker\machine\machines\default --name default --register
(default) DBG | STDOUT:
(default) DBG | {
(default) DBG | Virtual machine 'default' is created and registered.
(default) DBG | UUID: a24ec4ac-f54d-49b9-bd22-9426325c6c79
(default) DBG | Settings file: 'C:\Users\Raphael\.docker\machine\machines\default\default\default.vbox'
(default) DBG | }
(default) DBG | STDERR:
(default) DBG | {
(default) DBG | }
(default) DBG | VM CPUS: 1
(default) DBG | VM Memory: 2048
(default) DBG | COMMAND: D:\Program Files\Oracle\VirtualBox\VBoxManage.exe modifyvm default --firmware bios --bioslogofadein off --bioslogofadeout off --bioslogodisplaytime 0 --biosbootmenu disabled --ostype Linux26_64 --cpus 1 --memory 2048 --acpi on --ioapic on --rtcuseutc on --natdnshostresolver1 off --natdnsproxy1 off --cpuhotplug off --pae on --hpet on --hwvirtex on --nestedpaging on --largepages on --vtxvpid on --accelerate3d off --boot1 dvd
(default) DBG | STDOUT:
(default) DBG | {
(default) DBG | }
(default) DBG | STDERR:
(default) DBG | {
(default) DBG | VBoxManage.exe: error: Code E_FAIL (0x80004005) - Unspecified error (extended info not available)
(default) DBG | VBoxManage.exe: error: Context: "LockMachine(a->session
 LockType_Write)" at line 493 of file VBoxManageModifyVM.cpp
 (default) DBG | }
Error creating machine: Error in driver during machine creation: D:\Program Files\Oracle\VirtualBox\VBoxManage.exe modifyvm default --firmware bios --bioslogofadein off --bioslogofadeout off --bioslogodisplaytime 0 --biosbootmenu disabled --ostype Linux26_64 --cpus 1 --memory 2048 --acpi on --ioapic on --rtcuseutc on --natdnshostresolver1 off --natdnsproxy1 off --cpuhotplug off --pae on --hpet on --hwvirtex on --nestedpaging on --largepages on --vtxvpid on --accelerate3d off --boot1 dvd failed:
VBoxManage.exe: error: Code E_FAIL (0x80004005) - Unspecified error (extended info not available) 
VBoxManage.exe: error: Context: "LockMachine(a->session
 LockType_Write)" at line 493 of file VBoxManageModifyVM.cpp 
 ```

__Error log from Docker Quickstart Terminal:__
```
Welcome to Portable Git (version 1.9.5-preview20150319)


Run 'git help git' to display the help index.
Run 'git help <command>' to display help for specific commands.
Running pre-create checks...
Creating machine...
(default) Copying C:\Users\Raphael\.docker\machine\cache\boot2docker.iso to C:\Users\Raphael\.docker\machine\machines\default\boot2docker.iso...
(default) Creating VirtualBox VM...
(default) Creating SSH key...
Error creating machine: Error in driver during machine creation: D:\Program Files\Oracle\VirtualBox\VBoxManage.exe modifyvm default --firmware bios --bioslogofadein off --bioslogofadeout off --bioslogodisplaytime 0 --biosbootmenu disabled --ostype Linux26_64 --cpus 1 --memory 1024 --acpi on --ioapic on --rtcuseutc on --natdnshostresolver1 off --natdnsproxy1 off --cpuhotplug off --pae on --hpet on --hwvirtex on --nestedpaging on --largepages on --vtxvpid on --accelerate3d off --boot1 dvd failed:
VBoxManage.exe: error: Code E_FAIL (0x80004005) - Unspecified error (extended info not available)
VBoxManage.exe: error: Context: "LockMachine(a->session, LockType_Write)" at line 493 of file VBoxManageModifyVM.cpp

Looks like something went wrong... Press any key to continue...
```

__Environment Variables:__
```
λ env | grep VBOX
VBOX_INSTALL_PATH=D:\Program Files\Oracle\VirtualBox\
VBOX_MSI_INSTALL_PATH=D:\Program Files\Oracle\VirtualBox\
```

__Network Adapters (Before Clean)__ (I believe there were from my Vagrant/Homestead installation)
![Network Adapters](https://cloud.githubusercontent.com/assets/2119933/12735896/b3fd68da-c932-11e5-9e18-de8e0fe2e434.png)


__Network Adapters (After Clean & Retry)__
![Network Adapters](https://cloud.githubusercontent.com/assets/2119933/12735894/ab85445c-c932-11e5-9080-6df5074173d9.png)

__Computer Info:__
- OS: Windows 10 x64

It is also worth noting that I already had msysGit installed an opted not to install the version that comes with Toolbox.

If there's anything else that I can provide to help, please let me know.

**Comment by FrenchBen** [comment]
Ping @nathanleclaire any idea what's going on here?

**Comment by yugou** [comment]
I have tried what you guys suggested **wipe out default VM and clean up Host-only Networks** # of times.  Always run into the same error, even now.

![vmdefaulterror2](https://cloud.githubusercontent.com/assets/8205302/12766273/4260d3a0-ca46-11e5-9942-1297d459bd4d.jpg)

**Comment by rmobis** [comment]
I tried installing it on another machine of mine and it worked perfectly. The only difference between both machines that I think could matter is that _i think_ I had already tried to install Docker on the first machine with Boot2Docker, a long time ago, without success.

**Comment by FrenchBen** [comment]
@rmobis I have seen 'older' Virtualbox versions creating havoc when trying to create a new version. Good to hear it works well on a vanilla machine. 
Unfortunately vbox upgrades aren't as smooth as one would hope - Hence the repeated advice to wipe the install clean then try again.

**Comment by yugou** [comment]
> Hence the repeated advice to wipe the install clean then try again.

Would you kindly telling me other than uninstalling of VBox, what needs to be done?
I mean which directories need to be removed, that created by VBox?

**Comment by FrenchBen** [comment]
@yugou I am probably not the best on vbox knowledge of 'clean' uninstall - I did however find this thread, which may help:
https://forums.virtualbox.org/viewtopic.php?f=8&t=68820

**Comment by FrenchBen** [comment]
@yugou Can you check and see if perhaps you have Hyper-V enabled?
See: https://github.com/docker/kitematic/issues/1399#issuecomment-180060648

**Comment by yugou** [comment]
@FrenchBen san
Hyper-V has not been enabled/installed on my Windows 10 system.

In case, disabled Intel HT and tried.

![dsc_0311](https://cloud.githubusercontent.com/assets/8205302/12861786/46041714-cca9-11e5-8e7d-28d2da00d164.jpg)

No luck, the same error.

**Comment by nathanleclaire** [comment]
@yugou Enabling hardware virtualization in the BIOS is different than checking if Hyper-V is configured.  You can see the Hyper-V setting in Windows menus (e.g. in Windows features http://windows.microsoft.com/en-us/windows-8/hyper-v-run-virtual-machines).

If your machine does not support Hyper-V it will simply be missing from the menu.

**Comment by yugou** [comment]
@nathanleclaire 
Windows10 Hypuer-V has not been enabled.
BIOS Hypuer-V you are talking about is shown as Intel Visualization Tech on my BIOS setting and that has been enabled since years ago.

**Comment by rmobis** [comment]
No Hyper-V here either:

![image](https://cloud.githubusercontent.com/assets/2119933/12863645/0edb9198-cc60-11e5-8c9d-39b82ab6e1b9.png)

**Comment by yugou** [comment]
@mobis　san
Arigatou.
I know Hyper-V menu on Windows Features and it has never been clicked, thus never installed.

**Comment by rmobis** [comment]
As per https://github.com/docker/kitematic/issues/1399#issuecomment-180530234, updating my Windows (even if that was quite troublesome) solved the issue.

**Comment by yugou** [comment]
My Windows 10 has been always updated and has been facing this issue under the latest Windows' update.

**Comment by conan** [comment]
I have the same problem, I fire up Kitematic and it creates a default Docker container, then I run `docker-machine start default` and get this:

    VBoxManage.exe: error: Context: "LockMachine(a->session, LockType_Write)" at line 493 of file VBoxManageModifyVM.cpp

I've tried reinstalling VirtualBox, running version 5.0.16-10.  I have two Host-only networks after installing VirtualBox, one at 192.168.99.1 and one at 192.168.56.1.  My Windows 10 is up to date, and I'm only running Windows Defender, no other antivirus.  My virtualisation is enabled.  I also use VirtualBox with Vagrant with no problems, and when I start that it adds another Host-only network on the IP address specified in my Vagrantfile.

**Comment by nathanleclaire** [comment]
> I think the problem was a mismatch between what was being reported by docker-machine and what was actually happening

Out of curiosity, when you saw this behavior, was the VM displaying "Saved" state in the VirtualBox GUI?

**Comment by krishnanandula** [comment]
I had the same issue recently , for me the virtualBox GUI ("default") showing state was running . I simply powered it off and then started my docker and everything works well.

**Comment by aniruddh02** [comment]
It worked for me by simply powering off the virtual machine (default) and restarting docker.

**Comment by andreikun** [comment]
Hello,

Please try to vagrant up or homestead or whatever vagrant or homestead command you need from a command line run as administrator. I fixed my own issue while trying to vagrant up and ssh my machine by hitting this commands from a command prompt as administrator.

Hope this will fix your issue.

This is especially for Windows users.

**Comment by rjfisher123** [comment]
Hello All,
I ran into this issue on a windows machine, here was my resolution path:
1. Start
2. Control Panel
3. Network and Internet
4. Network and Sharing Center
5. Change adapter settings (Left hand menu)
6. Right click "Virtual Host-Only Network" adapter (or all applicable adapters for "Virtual"
7. Select Properties (click through admin control)
8. Select Configure button
9. Select Driver tab
10. Select Update Driver button
11. Select "Browse my computer for driver software"
12. Select "Let me pick from a list of device drivers on my computer"
13. Select "VirtualBox Host-only Ethernet Adapter" (select Next and Ok all prior windows)
14. run docker-machine start [your vm] :-)

**Comment by shainad** [comment]
@rjfisher123 I went through the resolution path you posted above; however, I am still receiving an error when trying to vagrant up...

![vagrant up error ssh](https://cloud.githubusercontent.com/assets/23282597/20032630/a08b07f0-a364-11e6-8232-2443e95017a5.JPG)

any ideas?

**Comment by Creased** [comment]
The `LockMachine(a->session, LockType_Write)` issue is due to a lack of administrator access token request by the command prompt or VirtualBox API client (i.e., Kitematic). Ideed, without administrator access token, client will not be able to override the machine's lock defined by VBoxHeadless elevated process and will return such this error.

Here is a way to solve this issue:

```batch
reg add "HKEY_CURRENT_USER\SOFTWARE\Microsoft\Windows NT\CurrentVersion\AppCompatFlags\Layers" /v "C:\Windows\System32\cmd.exe" /t REG_SZ /d "~ RUNASADMIN" /f
reg add "HKEY_CURRENT_USER\SOFTWARE\Microsoft\Windows NT\CurrentVersion\AppCompatFlags\Layers" /v "C:\Windows\SysWOW64\cmd.exe" /t REG_SZ /d "~ RUNASADMIN" /f
reg add "HKEY_CURRENT_USER\SOFTWARE\Microsoft\Windows NT\CurrentVersion\AppCompatFlags\Layers" /v "C:\Program Files\Oracle\VirtualBox\VirtualBox.exe" /t REG_SZ /d "~ RUNASADMIN" /f
reg add "HKEY_CURRENT_USER\SOFTWARE\Microsoft\Windows NT\CurrentVersion\AppCompatFlags\Layers" /v "C:\Program Files\Docker Toolbox\kitematic\Kitematic.exe" /t REG_SZ /d "~ RUNASADMIN" /f

reg add "HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows NT\CurrentVersion\AppCompatFlags\Layers" /v "C:\Windows\System32\cmd.exe" /t REG_SZ /d "~ RUNASADMIN" /f
reg add "HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows NT\CurrentVersion\AppCompatFlags\Layers" /v "C:\Windows\SysWOW64\cmd.exe" /t REG_SZ /d "~ RUNASADMIN" /f
reg add "HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows NT\CurrentVersion\AppCompatFlags\Layers" /v "C:\Program Files\Oracle\VirtualBox\VirtualBox.exe" /t REG_SZ /d "~ RUNASADMIN" /f
reg add "HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows NT\CurrentVersion\AppCompatFlags\Layers" /v "C:\Program Files\Docker Toolbox\kitematic\Kitematic.exe" /t REG_SZ /d "~ RUNASADMIN" /f
```

**Comment by hanaamohamed** [comment]
i had the exact issue because i was trying to edit it through cmd and the vm already started you need to close it and try again.

**Comment by tgatev** [comment]
The key point is "Run as Administrator", run your VirtualBox or Terminal as administrator, in other case you have no write permissions.

**Comment by daramir** [comment]
I ran Creased's regedits to no avail :(

**Comment by cihanbas** [comment]
@tgatev 
thanks bro 
" Run as Administraton"  it is working
