### ISSUE TITLE
Docker Quickstart Terminal returns no such file or directory on .pem file

### ISSUE THREAD

**Issue by moxiegirl** [docker/toolbox#46]
![image](https://cloud.githubusercontent.com/assets/1347209/9029483/dda18416-3948-11e5-908f-85a5868b82a6.png)

Mac OS X
rc3

![image](https://cloud.githubusercontent.com/assets/1347209/9029488/01c7f8de-3949-11e5-9796-641816d69885.png)

This problem doesn' t happen in a regular terminal

**Comment by jeffdm** [comment]
Fixed in rc4 since it's back to using Boot2Docker TCL

**Comment by moxiegirl** [comment]
I'm still seeing prompt_git:command_not found installing with rc4

![image](https://cloud.githubusercontent.com/assets/1347209/9075817/515c5d6e-3ace-11e5-928b-90087c00c726.png)

**Comment by jeffdm** [comment]
Just to follow up on this:

This may be related to your bash prompt setup. The quickstart terminal isn't doing anything out of the ordinary. It's only running `bash` and then some `docker-machine` commands.

For the missing `ca.pem`, please open a ticket on https://github.com/docker/machine.

Closing for now since I don't think this is related to the Toolbox, but feel free to re-open!
