### ISSUE TITLE
docker mounts not working with boot2docker v19.03.0

### ISSUE THREAD

**Issue by dhohengassner** [docker/toolbox#844]
Created a VM using docker-machine create today. It seems file mounts into docker containers are not working. The reason seems to be that docker-machine grabs the latest boot2docker image - https://github.com/boot2docker/boot2docker/releases/tag/v19.03.0

Pinned the version now to v18.09.8 and mounts are working again.

This is easy to reproduce:
```
docker run --rm -it -v $PWD:/src --entrypoint sh alpine:latest
ls /src
```

Any help or fix is much appreciated!

**Comment by Try-Parser** [comment]
I have the same issue just got upgraded my client from 18.03 to 18.09.3 and my Engine to 19.03 

i checked the container where i mount my directories from host path to container paths and it thinks it is mounted but the files are not and i thinks the files are cleaned 

```[
    {
        "Id": "78d26dbf181c8b32e28be0121014b67acf83a81567c75689d78b311f52898a25",
        "Created": "2019-07-26T06:23:11.18197734Z",
        "Path": "npm",
        "Args": [
            "run",
            "serve"
        ],
        "State": {
            "Status": "restarting",
            "Running": true,
            "Paused": false,
            "Restarting": true,
            "OOMKilled": false,
            "Dead": false,
            "Pid": 0,
            "ExitCode": 254,
            "Error": "",
            "StartedAt": "2019-07-26T06:23:41.412788155Z",
            "FinishedAt": "2019-07-26T06:23:41.748712133Z"
        },
        "Image": "sha256:f633392a5659ae552b801473a238a2747b9533b6cdef6e50bb49f008317b54a5",
        "ResolvConfPath": "/mnt/sda1/var/lib/docker/containers/78d26dbf181c8b32e28be0121014b67acf83a81567c75689d78b311f52898a25/resolv.conf",
        "HostnamePath": "/mnt/sda1/var/lib/docker/containers/78d26dbf181c8b32e28be0121014b67acf83a81567c75689d78b311f52898a25/hostname",
        "HostsPath": "/mnt/sda1/var/lib/docker/containers/78d26dbf181c8b32e28be0121014b67acf83a81567c75689d78b311f52898a25/hosts",
        "LogPath": "/mnt/sda1/var/lib/docker/containers/78d26dbf181c8b32e28be0121014b67acf83a81567c75689d78b311f52898a25/78d26dbf181c8b32e28be0121014b67acf83a81567c75689d78b311f52898a25-json.log",
        "Name": "/eschool_clientserver_1",
        "RestartCount": 9,
        "Driver": "overlay2",
        "Platform": "linux",
        "MountLabel": "",
        "ProcessLabel": "",
        "AppArmorProfile": "",
        "ExecIDs": null,
        "HostConfig": {
            "Binds": [
                "/c/Users/Try-Parser/Desktop/Eschool/is-client:/usr/is-client:rw"
            ],
            "ContainerIDFile": "",
            "LogConfig": {
                "Type": "json-file",
                "Config": {}
            },
            "NetworkMode": "eschool_default",
            "PortBindings": {
                "8080/tcp": [
                    {
                        "HostIp": "",
                        "HostPort": "80"
                    }
                ]
            },
            "RestartPolicy": {
                "Name": "always",
                "MaximumRetryCount": 0
            },
            "AutoRemove": false,
            "VolumeDriver": "",
            "VolumesFrom": [],
            "CapAdd": null,
            "CapDrop": null,
            "Capabilities": null,
            "Dns": null,
            "DnsOptions": null,
            "DnsSearch": null,
            "ExtraHosts": null,
            "GroupAdd": null,
            "IpcMode": "shareable",
            "Cgroup": "",
            "Links": null,
            "OomScoreAdj": 0,
            "PidMode": "",
            "Privileged": false,
            "PublishAllPorts": false,
            "ReadonlyRootfs": false,
            "SecurityOpt": null,
            "UTSMode": "",
            "UsernsMode": "",
            "ShmSize": 67108864,
            "Runtime": "runc",
            "ConsoleSize": [
                0,
                0
            ],
            "Isolation": "",
            "CpuShares": 0,
            "Memory": 0,
            "NanoCpus": 0,
            "CgroupParent": "",
            "BlkioWeight": 0,
            "BlkioWeightDevice": null,
            "BlkioDeviceReadBps": null,
            "BlkioDeviceWriteBps": null,
            "BlkioDeviceReadIOps": null,
            "BlkioDeviceWriteIOps": null,
            "CpuPeriod": 0,
            "CpuQuota": 0,
            "CpuRealtimePeriod": 0,
            "CpuRealtimeRuntime": 0,
            "CpusetCpus": "",
            "CpusetMems": "",
            "Devices": null,
            "DeviceCgroupRules": null,
            "DeviceRequests": null,
            "KernelMemory": 0,
            "KernelMemoryTCP": 0,
            "MemoryReservation": 0,
            "MemorySwap": 0,
            "MemorySwappiness": null,
            "OomKillDisable": false,
            "PidsLimit": null,
            "Ulimits": null,
            "CpuCount": 0,
            "CpuPercent": 0,
            "IOMaximumIOps": 0,
            "IOMaximumBandwidth": 0,
            "MaskedPaths": [
                "/proc/asound",
                "/proc/acpi",
                "/proc/kcore",
                "/proc/keys",
                "/proc/latency_stats",
                "/proc/timer_list",
                "/proc/timer_stats",
                "/proc/sched_debug",
                "/proc/scsi",
                "/sys/firmware"
            ],
            "ReadonlyPaths": [
                "/proc/bus",
                "/proc/fs",
                "/proc/irq",
                "/proc/sys",
                "/proc/sysrq-trigger"
            ]
        },
        "Mounts": [
            {
                "Type": "bind",
                "Source": "/c/Users/Try-Parser/Desktop/Eschool/is-client",
                "Destination": "/usr/is-client",
                "Mode": "rw",
                "RW": true,
                "Propagation": "rprivate"
            }
        ]
    }
]```

we got a temporary fix for it just downgrade your toolbox to 18.03. but i would like to know also the fix for 19.03

**Comment by Try-Parser** [comment]
i found a little fix about this issue just dont use 19.03 Boot2Docker you can use that version 18.09.8 since 19.03 is 3 days ago the toolbox upgrading to the latest version..

```
docker-machine create --driver "virtualbox" --virtualbox-boot2docker-url https://github.com/boot2docker/boot2docker/releases/download/v18.09.8/boot2docker.iso default
```

**Comment by mrhappytech** [comment]
I have the same problem. Any version of 19.03.0 till today is with that error. It prevents use volumes with docker-compose. Re-installation of Docker Toolbox will not help in the case you will install it with v19.03.x. Because Docker Quickstart Terminal will always download new version of Boot2Docker you must unplug your internet for that moment and plug the cable back when it is waiting for IP address. Cheers.

**Comment by kainxspirits** [comment]
I think it has been fixed on latest version (v19.03.1)

**Comment by mrhappytech** [comment]
Maybe, I re-installed the Boot2Docker yesterday and it was still doing that problem. So probably it is not fixed completely. With version v18.09.3 it is working OK.

**Comment by kainxspirits** [comment]
I mean, with the latest version of toolbox : https://github.com/docker/toolbox/releases/tag/v19.03.1.

Installers are not available yet, but you can easily build them by following those steps : https://github.com/docker/toolbox/tree/v19.03.1#building-the-docker-toolbox.

**Comment by CollinChaffin** [comment]
This is a big issue and the fix is simply install .1 yet for some reason after days it's the only version so far that installers have not be built hopefully they will be posted soon.

**Comment by theque5t** [comment]
Suggestion from @Try-Parser resolved this for me

**Comment by weeix** [comment]
I can still reproduce this issue with Docker Toolbox 19.03.1 and Boot2Docker 19.03.1:

```
ME@MYCOM MINGW64 ~/Documents/GitProj/flask_test (master)
$ ls app
app.py*  library/  requirements.txt  static/  templates/  uwsgi.ini

ME@MYCOM MINGW64 ~/Documents/GitProj/flask_test (master)
$ docker run --rm -it -v ${PWD}/app:/app alpine sh
/ # ls /app
/ #
```

**Comment by horvathd** [comment]
Updating VirtualBox to the latest 6.0.10 solved this issue for me.

**Comment by blacktear** [comment]
thinks! @horvathd @dhohengassner 
Updating VirtualBox to the latest version (6.0.10) solved this issue for me.

**Comment by fenicento** [comment]
> thinks! @horvathd @dhohengassner
> Updating VirtualBox to the latest version (6.0.10) solved this issue for me.

Same here, 6.0.10 solves the issue. Any chance that it will be included in a new release soon?

**Comment by guillaumerose** [comment]
Hello,

Yesterday @ulrich upgraded VirtualBox and made some tests. It seems to work fine for him now. So I merged the PR. Could you double-check and try this build ? If it's ok, I will do the release next week.

https://download-stage.docker.com/desktop/toolbox/844/DockerToolbox.pkg
https://download-stage.docker.com/desktop/toolbox/844/DockerToolbox.exe

Thanks!

**Comment by fenicento** [comment]
> Hello,
> 
> Yesterday @ulrich upgraded VirtualBox and made some tests. It seems to work fine for him now. So I merged the PR. Could you double-check and try this build ? If it's ok, I will do the release next week.
> 
> https://download-stage.docker.com/desktop/toolbox/844/DockerToolbox.pkg
> https://download-stage.docker.com/desktop/toolbox/844/DockerToolbox.exe
> 
> Thanks!

I'm having an issue when running docker quickstart terminal. When creating and running the virtual machine, I get

`Failed to open/create the internal network 'HostInterfaceNetworking-VirtualBox Host-Only Ethernet Adapter #2 ' (VERR_INTNET_FLT_IF_NOT_FOUND).`

this seems related to [this bug](https://www.virtualbox.org/ticket/14832), and disabling and enabling again the adapter does the job. Apart from this, volumes get mounted correctly and everything seems to work fine for now.

**Comment by ulrich** [comment]
OK, thank you for your feedback. @guillaumerose and I will plan the release this week so.

**Comment by semiromid** [comment]
I am experiencing a problem on VirtualBox version 6.0.14

**Comment by BoGnY** [comment]
The solution is deleting all "VirtualBox Host-Only Ethernet Adapter" in network cards' section in the "Device manager" of Windows 10 Control Panel 👍
